### ISSUE TITLE
Write binary format version together with each serialized tag

### ISSUE THREAD

**Issue by pshirshov** [zio/izumi-reflect#1]
This may allow us to maintain backward compatibility. It won't be easy - but will be possible.

See `makeParsedLightTypeTagImpl`

**Comment by neko-kai** [comment]
We can just append version number to the method name, e.g. call `LightTypeTag.parseV1(_, _)` in current macro, in next macro call `LightTypeTag.parseV2(_, _)`, while keeping support for `parseV1`. This also allows changing the types & parameters for next version.

**Comment by neko-kai** [comment]
@pshirshov 
This is done? `parse` currently accepts a version parameter:
```scala
def parse[T](hashCode: Int, refString: String, basesString: String, @unused version: Int)
```
