### ISSUE TITLE
Dotty: support assembling polymorphic tags (TagMacro)

### ISSUE THREAD

**Issue by neko-kai** [zio/izumi-reflect#103]
referred in https://github.com/zio/zio/issues/3816

>  I used dotty before 2.13.2 and didn't notice that they were missing. The dotty-compiler did not complain and is able to compile the same code without the necessary implicits.

There's a fairly involved piece of logic, `TagMacro`, in izumi-reflect that takes care of combining available `: Tag` evidences into types at runtime, by recursively doing implicit lookups for type parameters encountered in the type structure.

This `TagMacro` simply does not exist for the dotty version, so until it's added the tag evidences will not be combined in Dotty. (Also dotty version allows invalid/unresolved types, such as those with type parameters to slip through without errors, that's related but separate)

For the case in your example this can actually be worked around by requesting a "preassembled" tag (this will also improve performance in general):

```scala

        def layer[A, D <: Container[A]](container: D)(implicit t: Tag[ContainerProvider[A, D]]): Layer[Nothing, ContainerProvider[A,D]] = 
            ZLayer.succeed{
                new Service[A,D]{
                    def provide: IO[Throwable, D] = IO.succeed(container)
                }
            }
```

**Comment by kitlangton** [comment]
I tried reimplementing a very simple version of Tag that does this. [It worked by calling `Expr.summon` when encountering a type parameter](https://github.com/zio/zio/pull/6026/files#diff-360ce69b033b20851302c098d93b21e15424ce9c0080c1d8a43be47260848619R75). I'm guessing, due to the complexity of this fully-powered tag, `Expr.summon` won't work here. It looks like this implementation pickles/unpickles the LightTypeTag rather than generating an `Expr[Tag]` anyhow.

Is there anything that can be done here? Happy to give it a shot if you have any guidance (if it is at all possible). Also, throwing an error with a helpful message would be a great stopgap; though I noticed that may not be possible due to zit-mock (https://github.com/zio/zio/issues/5421#issuecomment-901397445). Perhaps there could be some special implicit import that could suppress the error.

**Comment by neko-kai** [comment]
@kitlangton 
> I'm guessing, due to the complexity of this fully-powered tag, Expr.summon won't work here. It looks like this implementation pickles/unpickles the LightTypeTag rather than generating an Expr[Tag] anyhow.

Expr.summon (or a lower-level tasty-reflect equivalent) should probably work here. There's no pickling/unpickling happening -  most of the time that's impossible to do since the content of the tag will only be known at runtime - instead calls to `Tag.appliedTag(ctorTag, List(argTags...))` are generated to assemble the tags from evidence at runtime.[[1]](https://github.com/zio/zio/pull/6026/files#diff-360ce69b033b20851302c098d93b21e15424ce9c0080c1d8a43be47260848619R75) (and to `HKTag.appliedTagNonPos` when runtime assembly must happen for a higher kinded type)

> though I noticed that may not be possible due to zit-mock. Perhaps there could be some special implicit import that could suppress the error.

It so happens that there's already a more permissive version of Tag available - `WeakTag` - it allows unresolved variables through even in Scala 2. Perhaps `zio-mock` could change its signatures to that - then Scala 3 version can drop its permissiveness workaround for regular Tag.

**Comment by pshirshov** [comment]
> this fully-powered tag

Oh, it's not fully-powered. It's just a _very minimal_ mock of the Scala typer. Actually, the only dirty/hard to comprehend part there is the Scala 2 type information extractor, the rest, including dotty extractor and runtime logic should be easy to read and mostly trivial.

> I tried reimplementing a very simple version of Tag that does this.

I'm not sure what's the purpose of that. In the end your implementation would be roughly the same as ours. I believe it would be lot cheaper to add some missing parts into `izumi-reflect` (in the end, 90% of the job is already done) though in case there are some other reasons for another implementation - I wouldn't mind, I think that our job was just to open the Pandora box of compile-time reflection.

**Comment by kitlangton** [comment]
> I'm not sure what's the purpose of that. In the end your implementation would be roughly the same as ours. I believe it would be lot cheaper to add some missing parts into `izumi-reflect`

Oh yeah. Definitely going to add the missing parts to `Izumi-refect`. It was mostly an exercise to explore if we needed the subtyping information at all—besides `zio-mock`, we don't really. However, we will in the future and, as you mention, so much of the work has been done. Nonetheless, it was a fun exercise 😄. 

> Expr.summon (or a lower-level tasty-reflect equivalent) should probably work here

That's great news. I'll give it a shot then.

**Comment by pshirshov** [comment]
Fixed in https://github.com/zio/izumi-reflect/pull/239
