### ISSUE TITLE
Unexpected result when summoning a Tag[X with X] (intersection type)

### ISSUE THREAD

**Issue by felher** [zio/izumi-reflect#12]
Hey folks,

I found some unexpected behavior when summoning a `Tag[String with String]`. Unexpected to me, that is. The example seems mostly academic but I stumbled upon it when experimenting with ZIO layers.

```scala
println(implicitly[Tag[String with String]])
```
prints `Tag[<refinement>]`. I'd expected that to either be `Tag[{String & String}]` or `Tag[String]`.

I dug around a bit and here's what I could find. The problem seems to originate in (call graph, top to bottom)

- `izumi.reflect.macrortti.LightTypeTagImpl#makeFullTagImpl`
- `makeRef` 
-  `unpack`
-  `unpackRefined`

There, the refinement is broken into parts. It can either be a `Broken.Single` or a `Broken.Compound`. The parts are split into a `Set(String, String)` which only has one element and so a `Broken.Single` is returned. The result is ignored and handled as if wasn't a refinement and eventually reduced to a `SymTypeName(izumi.reflect.Main.<refinement>)`.

I'm not sure how best to fix it. Ignoring the result of `breakRefinement` in case of a `Broken.Single` seems to be intentional:
>           // we intentionally ignore breakRefinement result here, it breaks lambdas

**Comment by pshirshov** [comment]
Hi! Thanks for the report, I'll try to look at it tomorrow.

**Comment by pshirshov** [comment]
I've fixed the problem another way, which, I think, is more straightforward.
