### ISSUE TITLE
TagMacro: Spurious tag inequality when parameterizing type alias of intersection

### ISSUE THREAD

**Issue by neko-kai** [zio/izumi-reflect#189]
See https://github.com/7mind/izumi/issues/1523#issuecomment-855781286

**Comment by pshirshov** [comment]
https://github.com/zio/izumi-reflect/blob/develop/izumi-reflect/izumi-reflect/src/test/scala/izumi/reflect/test/SharedTagProgressionTest.scala#L27

**Comment by neko-kai** [comment]
Has associated progression test `"progression test: reported in https://github.com/zio/izumi-reflect/issues/189, parameterized type alias with intersection produces incorrect output"` https://github.com/zio/izumi-reflect/blob/c0afe1b837acae5a72b10e0e0fe571edac69b2ed/izumi-reflect/izumi-reflect/src/test/scala/izumi/reflect/test/SharedTagProgressionTest.scala#L29

**Comment by neko-kai** [comment]
Relevant branch https://github.com/7mind/izumi/commits/feature/fix-type-alias-with
