### ISSUE TITLE
Dotty port feature request: tasty file reader

### ISSUE THREAD

**Issue by gzoller** [zio/izumi-reflect#2]
I’ve read you may be porting this library to Dotty.  If true, I have a request.  Dotty has two kinds of reflection: static compile-time reflection based on macros/metaprogramming, and inspection based on reading .tasty files.  When you port, could you support both?

Actually (selfishly) I’m really only interested in Tasty inspection as a basis for a reflection library.  My use case is runtime-specific, and as you know Dotty dumped the typetag and runtime reflection.  At runtime my program gets a fully qualified classname, then I need to reflect on it—which I do today with reflection and typetags.

I’m also working on a Dotty reflection library that uses Tasty inspection to get as far as possible, then try to blend with Java runtime reflection to fill in any gaps.  It’s a work in progress.  One area of weakness in my library is I can’t use <:< or similar operators, and instead have to do a lot of unfortunate string comparisons.  I’d love features like you have in this library if it worked outside a macro at runtime.

An example of my use case, JSON parsing for traits:
```
{“_hint”:”com.myatuff.Foo”,”field1”:”val1”,...}
```
My parser today in 2.13 with typetags would read the json and find the hint, then reflect on class Foo to get details on fields and types to know how to parse the rest of the json.  This use case is why macros wouldn’t work for me.  I don’t know what classes I need to reflect on at compile time—not until I receive some json input.

Best with your port!

**Comment by neko-kai** [comment]
@gzoller 
It may be nontrivial to support reading tasty right away, but we're open to pull requests that would add this ability. The current exploration of dotty typetags is happening here - https://github.com/pshirshov/dotty-typetag-research

> then reflect on class Foo to get details on fields and types to know how to parse the rest of the json.

Note that `LightTypeTag` as implemented here does _not_ contain any information about fields or methods, it supports type comparison with `<:<` and `=:=` and several symbolic operations on type descriptors, but it does not fully replace `TypeTag`.
Most likely you'll have to create your own reader to support methods & fields.

**Comment by pshirshov** [comment]
For now we are going to rely purely on compile-time inspection as per that's the easiest (if not only) way to achieve the goal. We have to be able to extract some data from scala typer to reuse it in our "mini-typer" later. It would be orders of magnitude harder to rely purely on tasty data.

**Comment by gzoller** [comment]
Actually <:< and similar would be very helpful!  Currently in Scala reflection TypeTag, do you know how they achieve this at runtime or just form classfile (wherever they get this info)?  They must have a way of doing this--they don't even have the "extra" stuff a .tasty file has.

**Comment by neko-kai** [comment]
@gzoller every scala entity has a `@ScalaReflection` annotation that contains the type information. This is used both for type-checking and for RTTI

**Comment by gzoller** [comment]
Wow--that doesn't seem like a lot, presuming the compiler generates these annotations.  It seems like it would be a small lift (for Dotty) to have some basic type info in such an annotation making some basic type operations straightforward.

**Comment by neko-kai** [comment]
@gzoller You can use Scala 2 libs from Dotty, so I assume it has all the necessary type operations – which then transports us back to the original problem, i.e. extracting type information from tasty files and/or compiler/macro APIs. Note, I think you don't have to parse tasty's by hand, there's a `tasty-inspector` lib published with dotty that I think exposes just the necessary compiler APIs for parsing/manipuliating tasty
