### ISSUE TITLE
Incorrect Tag[Map[K, A]] Derived From Tag[K] and Tag[A] on Scala 3

### ISSUE THREAD

**Issue by adamgfraser** [zio/izumi-reflect#208]
Ran into this issue when working on zio/zio#5481 with methods like this

```scala
def getAt[K, A](k: K)(implicit ev: Self <:< HasMany[K, A], keyTag: Tag[K], valueTag: Tag[A]): Option[A] = {
   val tag = taggedTagType(Tag[Map[K, A]])

  ???
}
```

On Scala 3 the `tag` is `Tag[Map[=_$K|<Nothing..Any>,+_$A|<Nothing..Any>]]` rather than the expected `Tag[Map[=String,+Int]]`. This works correctly on Scala 2.

I know there is an ongoing effort to build out functionality for Scala 3 so not sure how that fits into that. Thanks again for all your work on this!

**Comment by neko-kai** [comment]
Fixed in https://github.com/zio/izumi-reflect/pull/239
