### ISSUE TITLE
Finish Dotty port

### ISSUE THREAD

**Issue by pshirshov** [zio/izumi-reflect#22]
Right now we are blocked by:

- [x] https://github.com/lampepfl/dotty/issues/8520 (variance)
- [x] https://github.com/lampepfl/dotty/issues/8514 (bases classes for applied type constructor)
- [x] https://github.com/lampepfl/dotty/issues/8764 (inability to analyze tree when current context type is inferred)

Things to do:

- [x] Support prefix extraction
- [x] Support variance extraction for all the cases

**Comment by pshirshov** [comment]
See: https://github.com/7mind/dotty-typetag-research/issues/2

**Comment by pshirshov** [comment]
At the moment we have `baseClasses` but it's not enough to introspect parameterized parents.
But this P/R should fix the issue: lampepfl/dotty#9481

**Comment by pshirshov** [comment]
Base classes support introduced in https://github.com/zio/izumi-reflect/pull/67

**Comment by bishabosha** [comment]
does closing lampepfl/dotty#8764 solve the problem described?

**Comment by neko-kai** [comment]
@bishabosha 
It appears so, at least the example from #135 starts passing after update to RC1 where blackbox macros were added.

**Comment by domdorn** [comment]
I'm sorry to ask, but is izumi-reflect already working with 3.0.0-RC1 ? if so, could you please publish a version, so that zio-core can upgrade? I'm in the unfortunate situation where my json lib needs RC1 to do its macros but zio is still at M3 and I cant mix two scala3 versions in one project.

**Comment by sideeffffect** [comment]
@domdorn we're working on it https://github.com/zio/zio/pull/4770 :wink:

**Comment by pshirshov** [comment]
Actually I think we may close this. We've achieved original goals and while there are some hiccups, the port itself if functional.
