### ISSUE TITLE
Release izumi-reflect for Scala Native - Scala 3

### ISSUE THREAD

**Issue by lolgab** [zio/izumi-reflect#287]
Support for Scala Native - Scala 3 was merged (https://github.com/zio/izumi-reflect/pull/267) but not released.
Can we have a release to unlock ZIO on Scala Native + Scala 3 ?

**Comment by sideeffffect** [comment]
Hi @neko-kai , I see that you have recently opened https://github.com/zio/izumi-reflect/pull/291 . After that gets merged, can we have a new release of izumi-reflect?

**Comment by neko-kai** [comment]
@sideeffffect Will do. Sorry for the delays.

**Comment by sideeffffect** [comment]
:pleading_face:

**Comment by neko-kai** [comment]
`2.1.1` is released for Scala Native + Scala 3. I couldn't find the time for a proper fix to #291, so this release is largely the same as `2.1.0`

**Comment by sideeffffect** [comment]
Thank you so much! :heart:
