### ISSUE TITLE
scala's Symbol.tree causing compile errors, it is not reliable and not recommended to use

### ISSUE THREAD

**Issue by johnduffell** [zio/izumi-reflect#307]
I originally raised this against zio core, but since further investigation in search of a workaround I realised it's a bug in this specific module, so closing [that original issue](https://github.com/zio/zio/issues/7072) in favour of this.

## Summary

Hello, we have been using ZIO and having trouble with compile errors on our project.  I have narrowed it down to the smallest project I can which requires 2 files and 2 layers.

See https://github.com/johnduffell/zio2-scala3-bug

## How to reproduce + information

1. `git clone git@github.com:johnduffell/zio2-scala3-bug.git`
2. `sbt clean;compile`

You will see a compiler error (truncated for space reasons)
```
[error] -- Error: /Users/john_duffell/code/zio2-scala3-bug/src/main/scala/Testing.scala:12:31 
[error] 12 |  val error = zioEffect.provide(layer1, layer2)
[error]    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]    |Exception occurred while executing macro expansion.
[error]    |java.lang.AssertionError: assertion failed: Cannot get tree of no symbol
[error]    |	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
```
for the full error log see the above repo's readme.

java -version
```
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode)
```
Also happens on corretto Amazon JVM.
These are on a 2018 macbook pro.

In the dotty docs, they strongly suggest to avoid the method Symbol.tree due to this kind of problem: https://docs.scala-lang.org/scala3/guides/macros/best-practices.html#avoid-symboltree
As per those docs I tried adding this compiller option `scalacOptions += "-Yretain-trees"` and that also seems to solve it.
Also see https://github.com/lampepfl/dotty/blob/3a4ac15f67e650e6c36395f38119ac05600d6684/library/src/scala/quoted/Quotes.scala#L3744-L3769

Please do let me know if I can help any more, I appreciate your time.

**Comment by pshirshov** [comment]
Thanks for reporting, though I don't think we can get rid of `.tree`.
I'll investigate eventually, but probably the only thing we can do is to improve the error message.

**Comment by johnduffell** [comment]
Thanks Paul, that makes sense - in that case my recommendation would be to add this instruction to the setup docs:
`scalacOptions += "-Yretain-trees"`
Then that would stop people hitting this bug.

**Comment by pshirshov** [comment]
Seems like `.termRef` may work as a substitute for `.tree`, though it's marked as `@experimental`, so I cannot practically use it.

**Comment by pshirshov** [comment]
Ok, I've removed some calls to `.tree` and your example now compiles.

I'm still unable to get rid of `.tree` completely, because there is still no way to access `TypeDef#rhs` and `DefDef#returnTpt`. Also I had to use java reflection in order to work around that stupid `@experimental` stuff.
