### ISSUE TITLE
newtypes not supported

### ISSUE THREAD

**Issue by jdegoes** [zio/izumi-reflect#309]
e.g. ZIO Prelude newtypes

**Comment by pshirshov** [comment]
Yeah, currently Scala 3 support is limited to Scala 2 feature subset. We'll get there... eventually, any help would be appreciated, I think this shouldn't be hard to implement, at least for the trivial cases.

**Comment by pshirshov** [comment]
In fact it looks like once we have PDTs working this should work too.

**Comment by neko-kai** [comment]
@jdegoes 
Is this on Scala 2 or Scala 3? Newtypes definitely work in Scala 2 test suite. The errors in linked ticket https://github.com/zio/zio-logging/issues/451 come from @kitlangton's intersection filtering macro - not from izumi-reflect. We need a repro for the issue

**Comment by pshirshov** [comment]
```scala
import zio.*
import izumi.reflect.macrortti.*
import zio.prelude.*

object Testing {
  object SomeNewType extends Newtype[String]
  type SomeNewType = SomeNewType.Type

  def main(args: Array[String]): Unit = {
    println(LTT[SomeNewType])
  }
}
```

Runs successfully on Scala 3 and produces

```
{Newtype::Base & Newtype::Tag}
```
