### ISSUE TITLE
`Defect in zio.Has: Could not find` when using `-Ykind-projector`

### ISSUE THREAD

**Issue by tellnobody1** [zio/izumi-reflect#376]
## Prerequisites:
* `scalaVersion := "3.3.0-RC3"`
* ZIO 1.0.18 (no evicted warnings on ZIO)
* `scalacOptions += "-Ykind-projector"`
* `zio-test`

## Steps to reproduce
* Define layer using kind projection, e.g. `ULayer[Has[org.http4s.HttpApp[Task[*]]]]`
* It could be other ZIO types, e.g. `RIO[Any, *]`
* Run spec which uses this layer

## Actual result
* Runtime error:
```scala
java.lang.Error: Defect in zio.Has: Could not find Kleisli[=λ %A → ZIO[-Any,+Throwable,+A],-Request[=λ %A → ZIO[-Any,+Throwable,+A]],=Response[=λ %A → ZIO[-Any,+Throwable,+A]]] inside Map(Kleisli[=λ %_$1 → ZIO[-Any,+Throwable,+_$1],-Request[=λ %_$1 → ZIO[-Any,+Throwable,+_$1]],=Response[=λ %_$1 → ZIO[-Any,+Throwable,+_$1]]] -> Kleisli(org.http4s.syntax.KleisliResponseOps$$Lambda$9467/0x00000001026d2840@2077cbe))
```

## Expected result
* No runtime errors

## Workaround
* Do not use kind projections for layers, e.g. `ULayer[Has[org.http4s.HttpApp[Task]]]` or `type AppIO[A] = RIO[Any, A]; ULayer[Has[org.http4s.HttpApp[AppIO]]]`

## Example
Code: https://github.com/tellnobody1/zio-example
Error: https://github.com/tellnobody1/zio-example/actions/runs/4211720156/jobs/7310251627#step:4:28

**Comment by pshirshov** [comment]
I guess that should be fixed when we implement https://github.com/zio/izumi-reflect/issues/321

I've started working on that in https://github.com/zio/izumi-reflect/pull/375, by preserving lambda contexts while traversing the types. In order to make the actual fix I just need to add renumbering rules alike to Scala 2
