### ISSUE TITLE
How to obtain `Tag`s for subtypes of a sealed trait?

### ISSUE THREAD

**Issue by winitzki** [zio/izumi-reflect#441]
Given a `Tag` for a sealed trait, I would like to find the `Tag`s for all its known subtypes. Right now I don't think this is possible. The main obstacle seems to be that `izumi-reflect` can't convert a `Class[_]` to a `Tag` (neither at compile time nor at run time, and even if there is a string literal describing a fully qualified class name). Is that right?

What I'd like is to have an API such as:

```scala
sealed trait Tr
final case object T1 extends Tr
final case class A(x: Int) extends Tr

val x: Set[Tag[_]] = Tag[Tr].knownSubclasses
```
Here's is what I'm trying to do to implement that:

```scala
import scala.language.experimental.macros
import scala.reflect.macros.blackbox.Context

import izumi.reflect.Tag

object Macros {
  def knownSubclasses[A]: List[Tag[_]] = macro knownSubclassesImpl[A]

  def knownSubclassesImpl[A:c.WeakTypeTag](c: Context): c.Tree = {
    import c.universe._
    val subclasses: Set[c.universe.Symbol] = c.weakTypeOf[A].typeSymbol.asClass.knownDirectSubclasses
    val tags = subclasses.map { subclass =>
     q"izumi.reflect.Tag.apply[${subclass.fullName}]" // This is wrong: Tag["stringy name"].
    }
    q"List(..$tags)"
  }
}

```

This doesn't do what I want. Although I do get a list of fully qualified class names, I cannot convert them to `izumi.reflect.Tag` because there is no such API. Also I am not able to figure out how to create a `Tag` given a fully qualified class name. I suppose I could use reflection to create a `Class[_]` value from its fully qualified name as a string, but I'm not sure how to proceed after that. Please advise!

**Comment by neko-kai** [comment]
@winitzki 
You should be able to do this using `shapeless.Coproduct` on Scala 2 or `Mirror` on Scala 3, without having to write a custom macro.

Also, for the macro, I think you may be able to obtain a valid typeSymbol using `.asType`:
```scala
q"izumi.reflect.Tag.apply[${subClass.asType}]"
```

Fixed macro, I just checked that it works:

```scala
import scala.language.experimental.macros
import scala.reflect.macros.blackbox.Context

import izumi.reflect.Tag

object Macro {
  def knownSubclasses[A]: List[Tag[_]] = macro knownSubclassesImpl[A]

  def knownSubclassesImpl[A:c.WeakTypeTag](c: Context): c.Tree = {
    import c.universe._
    val subclasses: Set[c.universe.Symbol] = c.weakTypeOf[A].typeSymbol.asClass.knownDirectSubclasses
    val tags = subclasses.map { subclass =>
     q"izumi.reflect.Tag.apply[${subclass.asType}]" // This is wrong: Tag["stringy name"].
    }
    q"List(..$tags)"
  }
}

```
```scala
sealed trait Tr
final case object T1 extends Tr
final case class A(x: Int) extends Tr

object appp extends App {
  println(Macro.knownSubclasses[Tr])
}
```
```
List(Tag[T1], Tag[A])
```

**Comment by winitzki** [comment]
@neko-kai  Thank you, this helps. Probably I'll just write a few macros to cover my use case.

One more question: If a sealed trait has type parameters, am I supposed to use `TagK`, `TagKK`, etc., for it and also for its subclasses? I suppose I can figure out whether the trait or its subclasses have type parameters.

Example that currently doesn't seem to work:

```scala
 sealed trait Tr[A]
 final case class X1[A](x: A)         extends Tr[A]
 final case class X2[A, B](x: A, y: B) extends Tr[B] // whatever

 Macros.knownSubclasses[Tr[_]]
```

With this, I get an error:

```
type arguments [X1] conform to the bounds of none of the overloaded alternatives of
 value apply: [T](cls: Class[_], tag0: izumi.reflect.macrortti.LightTypeTag): izumi.reflect.Tag[T] <and> [T](implicit evidence$1: izumi.reflect.Tag[T]): izumi.reflect.Tag[T]
```

Do I need to reflect on the type symbol for each subclass to figure out whether it has type parameters, and how many, and then use the corresponding constructor from izumi-reflect?

**Comment by winitzki** [comment]
So far, I got this to work:

```scala
import scala.language.experimental.macros
import scala.reflect.macros.blackbox

object Macros {
  def knownSubclasses[A]: List[AnyTag] = macro knownSubclassesImpl[A]

  def knownSubclassesImpl[A: c.WeakTypeTag](c: blackbox.Context): c.Tree = {
    import c.universe._

    val subclasses: Set[c.universe.Symbol] = c.weakTypeOf[A].typeSymbol.asClass.knownDirectSubclasses

    val tags = subclasses.map { subclass =>
      subclass.asType.typeParams.length match {
        case 0 => q"izumi.reflect.Tag.apply[${subclass.asType}]"
        case 1 => q"izumi.reflect.TagK.apply[${subclass.asType.toTypeConstructor.typeSymbol}]"
        case 2 => q"izumi.reflect.TagKK.apply[${subclass.asType.toTypeConstructor.typeSymbol}]"
      }
    }
    q"List(..$tags)"
  }
}
```

This works with the `Tr[A]` example shown above.

The next step is to have a function `knownSubclasses: izumi.reflect.AnyTag => List[AnyTag]`. I suppose this requires runtime reflection on `closestClass.getPermittedSubclasses` (but this requires JDK17+). Then somehow I need to convert a `Class[_]` value into an `AnyTag`. Any hints would be appreciated. I will close this issue.

**Comment by neko-kai** [comment]
@winitzki I'm not sure you can extract subclasses from a Java class at all. JVM 11+ has class "nestmates", but I'm not sure if Scala marks them in resulting bytecode, I would guess that even if it does, you would have to compile for JDK 11+ (`-release:11` scalac option)

**Comment by winitzki** [comment]
JDK 17+ has the concept of "sealed interfaces", so it added a reflection API to get all known subclasses. But this is not quite what I need. 

I'm not sure it is possible at all to convert a given `Class[_]` value at runtime to an izumi `Tag`. 

In any case, thank you for your help!
