### ISSUE TITLE
Publish Project Docs On Release Events

### ISSUE THREAD

**Issue by khajavi** [zio/izumi-reflect#458]
The [last published documentation](https://www.npmjs.com/package/@zio.dev/izumi-reflect/v/2.2.3?activeTab=versions) of this project corresponds to `2.2.3`.

We need to update the CI to publish docs when a release event occurs. Please refer to [this link](https://zio.dev/contributing-to-zio-ecosystem#publishing-documentation) for more information.

This fixes the issue reported [here](https://github.com/zio/zio/issues/7678).

**Comment by pshirshov** [comment]
It works now but I had to finish the job myself :(

**Comment by pshirshov** [comment]
It seems like the publishing job works, the rest is on the zio team I guess: https://www.npmjs.com/package/@zio.dev/izumi-reflect/v/2024.11.10-2c4e2071d1e3?activeTab=code
