### ISSUE TITLE
Tag[Any] <:< Tag[Object] should not return true

### ISSUE THREAD

**Issue by hearnadam** [zio/izumi-reflect#500]
Izumi seems to diverge from the compiler:

```scala
import izumi.reflect.Tag

summon[Any <:< Object] // fails to compile
Tag[Any] <:< Tag[Object] // returns true
```

**Comment by neko-kai** [comment]
@hearnadam This is a known limitation. See point 6: https://github.com/zio/izumi-reflect/blob/ce4423541a4372349fca0dabae8ad68e2236df57/README.md#limitations

**Comment by hearnadam** [comment]
Ah I wasn't aware, thanks for the fast response.
