### ISSUE TITLE
Dotty: run the Scala 2 test suite 

### ISSUE THREAD

**Issue by neko-kai** [zio/izumi-reflect#57]
Currently the only test running for Dotty is an [extremely rudimentary small test](https://github.com/zio/izumi-reflect/blob/7e6a49b/izumi-reflect/izumi-reflect/src/test/scala/izumi/reflect/test/CurrentDottySupportExtentTest.scala), we should evolve the dotty implementation and port the Scala 2 test suite to the Scala 3 cross-build.

**Comment by pshirshov** [comment]
Partially done in https://github.com/zio/izumi-reflect/pull/67

**Comment by neko-kai** [comment]
Mostly done in https://github.com/zio/izumi-reflect/pull/244
