### ISSUE TITLE
false positive in equality test

### ISSUE THREAD

**Issue by IndiscriminateCoding** [zio/izumi-reflect#71]
```scala
import izumi.reflect._

import scala.{Int => ScalaInt}

private object scala {
  trait Int
  type X = this.Int
}

object Example extends App {
  assert(Tag[ScalaInt].tag != Tag[scala.X].tag) // :(
}
```

This specific example is somewhat artificial, but I'm not sure if it is **not** possible to hit this issue when using different libraries which use the same package name.

**Comment by neko-kai** [comment]
Hmm, it's generally not legal in Scala to have multiple types with the same fully-qualified name. You can achieve this inconsistency sometimes by using package objects & incremental compilation (compiler will sometimes not detect collisions in incremental compilation, that it subsequently detects on full rebuild), but you should probably hit compiler errors from this way before you hit errors in izumi-reflect.

**Comment by IndiscriminateCoding** [comment]
Ok, makes sense. I'm closing the issue
