### ISSUE TITLE
[dotty] malformed tags for type parameters are being generated instead of causing compile failures

### ISSUE THREAD

**Issue by IndiscriminateCoding** [zio/izumi-reflect#77]
Following example causes compilation error on scala2 (which is correct), while on dotty it happily infers `Tag[Any]`:

```scala
import izumi.reflect.Tag

object Main extends App {
  def f[A] = println(Tag[A])
  f[Int] // Tag[Any]?
}
```

**Comment by neko-kai** [comment]
The logic that should filter out "weak" components of a type and try to resolve them (or fail trying) is not yet implemented for Scala 3: https://github.com/zio/izumi-reflect/issues/103, that would fix the issue

**Comment by pshirshov** [comment]
Should be fixed now.
